//! Trading Strategies — Signal Generation
//!
//! Strategies ranked by profitability:
//! 1. Pair Arbitrage (risk-free, UP+DOWN < $1)
//! 2. BTC Volume Sniper (86.9% WR)
//! 3. GTC Deep Limit (asymmetric R/R, TODO)
//!
//! All strategies run in PARALLEL via tokio::join! for sub-ms execution.

pub mod volume_sniper;
pub mod pair_arb;

use crate::data::gamma::Market;
use crate::data::clob::ClobClient;

/// A trading signal generated by a strategy
#[derive(Debug, Clone)]
pub struct Signal {
    pub strategy: String,
    pub coin: String,
    pub direction: String,      // "UP" or "DOWN"
    pub token_id: String,
    pub market_id: String,
    pub entry_price: f64,
    pub confidence: f64,
    pub order_type: String,     // "maker" or "taker"
    pub rationale: String,
    pub agreement_count: u32,
    pub conviction_tier: String,
    pub seconds_remaining: f64,
}

/// Strategy engine — runs all strategies in PARALLEL (sub-ms)
pub struct StrategyEngine {}

impl StrategyEngine {
    pub fn new() -> Self {
        Self {}
    }

    /// Run all strategies against discovered markets
    /// Uses tokio::join! for true parallel execution (not sequential)
    pub async fn generate_signals(&self, markets: &[Market], clob: &ClobClient) -> Vec<Signal> {
        let mut all_signals = Vec::with_capacity(markets.len() * 2);

        for market in markets {
            // Run BOTH strategies concurrently on each market
            let (vol_sig, arb_sig) = tokio::join!(
                volume_sniper::analyze(market, clob),
                pair_arb::analyze(market, clob),
            );

            // Pair arb has HIGHEST priority (risk-free profit)
            if let Some(sig) = arb_sig {
                all_signals.push(sig);
            }
            if let Some(sig) = vol_sig {
                all_signals.push(sig);
            }
        }

        // Sort: pair_arb first (risk-free), then by confidence
        all_signals.sort_by(|a, b| {
            // Pair arb always wins priority
            let a_is_arb = a.strategy == "pair_arb";
            let b_is_arb = b.strategy == "pair_arb";
            if a_is_arb && !b_is_arb { return std::cmp::Ordering::Less; }
            if !a_is_arb && b_is_arb { return std::cmp::Ordering::Greater; }
            // Then by confidence
            b.confidence.partial_cmp(&a.confidence).unwrap_or(std::cmp::Ordering::Equal)
        });

        all_signals
    }
}
