//! Trading Strategies — Signal Generation
//!
//! 13 strategies ported from Python, starting with the most profitable:
//! 1. BTC Volume Sniper (86.9% WR)
//! 2. GTC Deep Limit (asymmetric R/R)

pub mod volume_sniper;

use crate::data::gamma::Market;
use crate::data::clob::ClobClient;

/// A trading signal generated by a strategy
#[derive(Debug, Clone)]
pub struct Signal {
    pub strategy: String,
    pub coin: String,
    pub direction: String,      // "UP" or "DOWN"
    pub token_id: String,
    pub market_id: String,
    pub entry_price: f64,
    pub confidence: f64,
    pub order_type: String,     // "maker" or "taker"
    pub rationale: String,
    pub agreement_count: u32,
    pub conviction_tier: String,
    pub seconds_remaining: f64,
}

/// Strategy engine — runs all strategies in parallel
pub struct StrategyEngine {
    // Strategies are functions, not trait objects (faster dispatch)
}

impl StrategyEngine {
    pub fn new() -> Self {
        Self {}
    }

    /// Run all strategies against discovered markets (parallel)
    pub async fn generate_signals(&self, markets: &[Market], clob: &ClobClient) -> Vec<Signal> {
        let mut all_signals = Vec::new();

        for market in markets {
            // BTC Volume Sniper (dominant strategy)
            if let Some(sig) = volume_sniper::analyze(market, clob).await {
                all_signals.push(sig);
            }

            // TODO: Port remaining 12 strategies
            // - hour_bias
            // - momentum_cascade
            // - indicator_fusion
            // - oracle_lead
            // - gtc_deep_limit
            // - microstructure_maker
            // - momentum_breakout
            // - quant_edge
            // - volume_imbalance
            // - mean_reversion
            // - maker_edge
            // - longshot_bias
        }

        // Sort by confidence (highest first)
        all_signals.sort_by(|a, b| b.confidence.partial_cmp(&a.confidence).unwrap_or(std::cmp::Ordering::Equal));
        all_signals
    }
}
